### PR TITLE
Feature/star2introns

### PR DESCRIPTION
**Pull request by thibauthourlier**
New "script" star2introns to load the junctions from STAR into an Ensembl database
Added pyproject.toml using peotry
Updated setup.py but it should probably be removed
Updated requirements.txt to specify versions for pymysql and sqlalchemy

### CODE REVIEW

**Comment by williamstark01** [comment]
@thibauthourlier The script looks good. Is there any missing functionality or is it complete?

For the changes in the config files, it would be good to give us an update so that everyone learns more about them in the first opportunity.

**Comment by thibauthourlier** [comment]
@williamstark01 I'm about to add some changes as the current script is using too much memory when using mutliple cores so I will add a single core option

**Comment by williamstark01** [comment]
@thibauthourlier That sounds good, I'll keep an eye on the PR then.

**Comment by williamstark01** [comment]
Is this PR still work in progress? If it is, how about [changing it to a draft PR](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-stage-of-a-pull-request#converting-a-pull-request-to-a-draft)? (Or, even better, close the PR and open a new one when the feature is ready for review.)

**Comment by thibauthourlier** [comment]
It was done and then it looks like the code is not doing the right thing

**Comment by thibauthourlier** [comment]
The build is failing because of Repeatmask_Red. I will update the module on a different branch when this is merged

**Review by ens-ftricomi — APPROVED** [review]
it's good

**Pull request merged**
