### PR TITLE
Update registry db and sheet when genebuild completes

### PR DESCRIPTION
**Pull request by ndliberial**
When annotation completes (that is after all abs have been finalised), we need to set the Genebuild to completed both in the registry db and the corresponding google sheets. This has been implemented in a script that now sits in the ensembl-genes repo

### CODE REVIEW

**Comment by williamstark01** [comment]
Hey Denye, could you [format the script with Black](https://www.ebi.ac.uk/seqdb/confluence/display/ENSGBD/Python#Python-codestyleandformatting) to clean up and adopt the standard formatting?

**Review by williamstark01 — CHANGES_REQUESTED** [review]
Hey Denye, good job. Could you [format the script with Black](https://www.ebi.ac.uk/seqdb/confluence/display/ENSGBD/Python#Python-codestyleandformatting) to clean up and adopt the standard formatting?

**Comment by ndliberial** [comment]
Thanks William for the link to Black.

**Comment by williamstark01** [comment]
No worries!

**Review by williamstark01 — APPROVED** [review]
Looking good now!

**Review by ndliberial — COMMENTED** [review]
@thibauthourlier, Kindly see the updated code and review if okay for approval

**Review by ndliberial — COMMENTED** [review]
Updated syntax error with main function

**Review by thibauthourlier — CHANGES_REQUESTED** [review]
These are questions:
- I don't think the notice should be staring with '..' but that is very pedantic and I could be wrong
- Should mysql.connector be added to the requirement file? ensembl-py uses sqlalchemy and mysqlclient, we should use the same for every module. (I know it's not true as we are using pymysql in Red for some reasons. What are the advantage compared to mysqlclient and sqlalchemy?
- As Black changed all my single quotes with double quotes on a different file, I'm surprise there are still single quotes in the file

The reason for the request:
there is duplicated code betwen the main function and the update_assembly_sheet function. Mainly connecting twice to the spreadsheet for no apparent reason

**Comment by ndliberial** [comment]
This is somewhat been overtaken by events. A lot has changed since when this was first initiated. Better to close and if need be make a fresh PR in the future.

**Comment by williamstark01** [comment]
Alright, you know best.

**Pull request closed without merging**
