### PR TITLE
Pylint suggested fixes

### PR DESCRIPTION
**Pull request by williamstark01**
Specify encoding when opening files. (fix for W1514)

Disable Pylint warning R1732 ("Consider using 'with' for resource-allocating operations (consider-using-with)"). It's a correct suggestion but it's not straightforward how to apply here, if at all possible.

### CODE REVIEW

**Comment by thibauthourlier** [comment]
If I understand correctly, it is tempfile causing the pylint call for "with". If in the end we still have to manually delete the directory, what is the benefit of using tempfile? We are already working in a specific directory so the need for uniqueness of the directory name is zero
The disable line in pylintrc is already quite long and it seems to me that we should use "with" when possible. I think it would be better to find a solution which would only affect the file itself rather than all the files of the repo

**Comment by williamstark01** [comment]
Fully agree on the length of the Pylint ignore list being too long, I converted the fix to a local ignore for just the instantiation of the temp directory. And it's probably a good idea to even study the global ignore list and shorten it further.

As for using the tempfile, not sure what the best approach here.

**Comment by ens-carlos** [comment]
Repeat Detector argument "gnm" points to a directory where all the fasta files would be processed. "tempfile.TemporaryDirectory" is used to make sure that only "genome_file" is processed by making a symlink to it from the temporary directory. It might be possible to wrap it around a "with" just to assign it to "gnm" or maybe there is some other alternative to "tempfile".

**Review by thibauthourlier — APPROVED** [review]
Looks good to me, a better solution would be to create a directory without tempfile to avoid the pylint message but manually disabling the message is a good option too

**Pull request merged**
