### PR TITLE
Repeatmask_Red module formatting and style

### PR DESCRIPTION
**Pull request by williamstark01**

### CODE REVIEW

**Comment by williamstark01** [comment]
@thibauthourlier I added an argument in the black check test to specify the max line length: https://github.com/Ensembl/ensembl-genes/pull/38/commits/4c76fcea1681c036abcfb13a2ea62ab81f1083a7

I see that the star2introns.py would be reformatted with this value, what line length are you using for formatting? I'm forgetting whether we made a team decision about the length to use, but I'm using 90 characters as a default.

**Comment by williamstark01** [comment]
@ens-carlos I formatted the Red module and did some minor styling changes in this PR in order to fix a few pylint errors during testing. There are a couple more remaining: https://app.travis-ci.com/github/Ensembl/ensembl-genes/jobs/569600903
I think in order to resolve the remaining issues we probably need to refactor the logic in a couple of places. Do you want to take this on since you understand the module better than anyone?

**Comment by ens-carlos** [comment]
Thanks William. Yes, I'll add some methods/functions to reduce the number of variables and statements per method and I'll rename the module so that it complies with the standard.

**Review by thibauthourlier — CHANGES_REQUESTED** [review]
Could you please revert the change to travis to use the default black parameters?
Could you also make pyling happy by adding pylint prgama controls inline? I don't think it's worth updating the code for the last errors but it can be done

**Comment by williamstark01** [comment]
@thibauthourlier Black defaults restored.

@ens-carlos let me know if I can help.

**Comment by ens-carlos** [comment]
I think it should be fine now in terms of the Red module.

**Review by thibauthourlier — APPROVED** [review]
Seems fine to me

**Pull request merged**
